// File generated by FlutterFire CLI.
// Modified to use environment variables for API keys.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get android {
    return FirebaseOptions(
      apiKey: dotenv.env['FIREBASE_ANDROID_API_KEY'] ?? '',
      appId: dotenv.env['FIREBASE_ANDROID_APP_ID'] ?? '',
      messagingSenderId: '716405823878',
      projectId: 'paw-around-f487d',
      storageBucket: 'paw-around-f487d.firebasestorage.app',
    );
  }

  static FirebaseOptions get ios {
    return FirebaseOptions(
      apiKey: dotenv.env['FIREBASE_IOS_API_KEY'] ?? '',
      appId: dotenv.env['FIREBASE_IOS_APP_ID'] ?? '',
      messagingSenderId: '716405823878',
      projectId: 'paw-around-f487d',
      storageBucket: 'paw-around-f487d.firebasestorage.app',
      iosClientId: dotenv.env['FIREBASE_IOS_CLIENT_ID'] ?? '',
      iosBundleId: 'com.pawaround.app',
    );
  }

  static FirebaseOptions get web {
    return FirebaseOptions(
      apiKey: "AIzaSyAVj8d0Ls_SYR_P67XJQlMSrK6MJFbkpM0",
      authDomain: "paw-around-f487d.firebaseapp.com",
      projectId: "paw-around-f487d",
      storageBucket: "paw-around-f487d.firebasestorage.app",
      messagingSenderId: "716405823878",
      appId: "1:716405823878:web:2139ecf13f8403e54a3407",
      measurementId: "G-R5H1LYCD0H",
    );
  }
}
